# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_image', models.FileField(upload_to='')),
                ('result_image', models.FileField(upload_to='')),
            ],
        ),
    ]
